name: Build all flavors

on:
  schedule:
    - cron: '0 3 1,14 * *'
  workflow_dispatch:

concurrency:
  group: 'biweekly-deploy'
  cancel-in-progress: false

jobs:
  build_time:
    name: Capture current time
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date.outputs.date }}
    steps:
      - name: Get date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

  versioning:
    name: Extract version
    runs-on: ubuntu-latest
    outputs:
      downstream: ${{ steps.downstream.outputs.version }}
      code: ${{ steps.downstream.outputs.code }}
      upstream: ${{ steps.upstream.outputs.version }}
    env:
      GITHUB_REPOSITORY: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Get downstream version
        id: downstream
        run: |
          echo "version=$(grep -E '^\s*versionName\s*=' composeApp/build.gradle.kts | awk -F '"' '{print $2}')" >> $GITHUB_OUTPUT
          echo "code=$(grep -E '^\s*versionCode\s*=' composeApp/build.gradle.kts | awk -F '= ' '{print $2}')" >> $GITHUB_OUTPUT

      - name: Get upstream version
        id: upstream
        run: |
          tag_name="$(curl -s https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest | jq -r .tag_name)"
          echo "version=${tag_name#v}" >> $GITHUB_OUTPUT

  verify-version:
    needs: [versioning]
    runs-on: ubuntu-latest
    steps:
      - name: Check if build can proceed
        run: |
          if [ "${{ needs.versioning.outputs.downstream }}" = "${{ needs.versioning.outputs.upstream }}" ]; then
            exit 1
          fi
      - name: Check changelog exists
        run: |
          if [ ! -e "fastlane/metadata/android/en-US/changelogs/${{ needs.versioning.outputs.code }}.txt" ]; then
            exit 1
          fi

  build-all:
    needs: [versioning, verify-version]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [GithubUncompressed, GithubRelease, IzzyRelease]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Setup Java 21
        uses: actions/setup-java@v5.0.0
        with:
          java-version: "21"
          distribution: "corretto"
      - name: Restore Gradle dependencies & build cache
        uses: actions/cache@v4.2.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./build
            ./composeApp/build
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-
      - name: Build APK
        run: |
          if [ "${{ matrix.flavor }}" == "GithubUncompressed" ]; then
            ./gradlew assembleGithubUncompressed
          elif [ "${{ matrix.flavor }}" == "GithubRelease" ]; then
            ./gradlew assembleGithubRelease
          else
            ./gradlew assembleIzzyRelease
          fi
      - name: Upload unsigned APKs
        uses: actions/upload-artifact@v4.6.2
        with:
          name: unsigned-${{ matrix.flavor }}
          path: |
            composeApp/build/outputs/apk/**/${{ matrix.flavor | lower }}/*.apk

  sign-apks:
    needs: build-all
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5.0.0
        with:
          path: upstream/unsigned
          merge-multiple: true
      - name: Sign APKs
        uses: Tlaster/android-sign@v1.2.2
        with:
          releaseDirectory: upstream/unsigned
          signingKeyBase64: "${{ secrets.KREATE_KEYSTORE }}"
          keyStorePassword: "${{ secrets.KREATE_KEYSTORE_PASSWD }}"
          alias: "${{ secrets.KREATE_KEY_ALIAS }}"
          keyPassword: "${{ secrets.KREATE_KEY_PASSWD }}"
          output: signed
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
      - name: Remove '-signed' suffix
        run: |
          for f in signed/*.apk; do mv "$f" "${f//-signed}"; done
      - name: Upload signed APKs
        uses: actions/upload-artifact@v4.6.2
        with:
          name: signed-apks
          path: signed/*.apk

  create-release:
    needs: [build_time, versioning, sign-apks]
    runs-on: ubuntu-latest
    steps:
      - name: Download signed APKs
        uses: actions/download-artifact@v5.0.0
        with:
          name: signed-apks
      - name: Generate unique tag
        id: tag
        run: |
          TAG="v${{ needs.versioning.outputs.downstream }}-${{ needs.build_time.outputs.date }}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
      - name: Create tag in repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.tag.outputs.tag }}
          git push origin ${{ steps.tag.outputs.tag }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: '*.apk'
          tag_name: ${{ steps.tag.outputs.tag }}
          name: ${{ steps.tag.outputs.tag }}
          make_latest: true
          body: |
            ## What's `Kreate-izzy.apk`

            This is APK built specifically for IzzyOnDroid with update checker disabled. You shouldn't
            download this version here.

            ## Verification
            Always check for signature before installing any APK.

            ## Changelogs
            Please visit [wiki/changelogs](https://github.com/knighthat/Kreate/wiki/Changelogs) for details.
          token: ${{ secrets.RELEASE_TOKEN }}
          generate_release_notes: true
