name: Build all flavors

on:
  schedule:
    - cron: '0 3 1,14 * *'
  workflow_dispatch:

concurrency:
  group: 'biweekly-deploy'
  cancel-in-progress: false

jobs:
  build_time:
    name: Capture current time
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date.outputs.date }}
    steps:
      - name: Get date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

  versioning:
    name: Extract version
    runs-on: ubuntu-latest
    outputs:
      downstream: ${{ steps.downstream.outputs.version }}
      code: ${{ steps.downstream.outputs.code }}
      upstream: ${{ steps.upstream.outputs.version }}
    env:
      GITHUB_REPOSITORY: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Get downstream (local) version
        id: downstream
        run: |
          echo "version=$(grep -E '^\s*versionName\s*=' composeApp/build.gradle.kts | awk -F '"' '{print $2}')" >> $GITHUB_OUTPUT
          echo "code=$(grep -E '^\s*versionCode\s*=' composeApp/build.gradle.kts | awk -F '= ' '{print $2}')" >> $GITHUB_OUTPUT
      - name: Get upstream version
        id: upstream
        run: |
          tag_name="$(curl -s https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest | jq -r .tag_name)"
          echo "version=${tag_name#v}" >> $GITHUB_OUTPUT

  verify-version:
    needs: [versioning]
    runs-on: ubuntu-latest
    steps:
      - name: Check if build can proceed
        run: |
          if [ "${{ needs.versioning.outputs.downstream }}" = "${{ needs.versioning.outputs.upstream }}" ]; then
            echo "No new version to release."
            exit 1
          fi
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Check changelog
        run: |
          if [ ! -e "fastlane/metadata/android/en-US/changelogs/${{ needs.versioning.outputs.code }}.txt" ]; then
            echo "Changelog not found."
            exit 1
          fi

  build-uncompressed:
    needs: [versioning, verify-version]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Setup Java 21
        uses: actions/setup-java@v5.0.0
        with:
          java-version: "21"
          distribution: "corretto"
      - name: Restore Gradle cache
        uses: actions/cache@v4.2.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./build
            ./composeApp/build
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-
      - name: Build APK
        run: ./gradlew assembleGithubUncompressed
      - name: Upload unsigned APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: unsigned-uncompressed
          path: composeApp/build/outputs/apk/github/uncompressed/*.apk

  build-release:
    needs: [versioning, verify-version]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Setup Java 21
        uses: actions/setup-java@v5.0.0
        with:
          java-version: "21"
          distribution: "corretto"
      - name: Restore Gradle cache
        uses: actions/cache@v4.2.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./build
            ./composeApp/build
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-
      - name: Build APK
        run: ./gradlew assembleGithubRelease
      - name: Upload unsigned APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: unsigned-release
          path: composeApp/build/outputs/apk/github/release/*.apk

  build-izzy:
    needs: [versioning, verify-version]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Setup Java 21
        uses: actions/setup-java@v5.0.0
        with:
          java-version: "21"
          distribution: "corretto"
      - name: Restore Gradle cache
        uses: actions/cache@v4.2.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./build
            ./composeApp/build
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-
      - name: Build APK
        run: ./gradlew assembleIzzyRelease
      - name: Upload unsigned APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: unsigned-izzy
          path: composeApp/build/outputs/apk/izzy/release/*.apk

  sign-apks:
    needs: [build-uncompressed, build-release, build-izzy]
    runs-on: ubuntu-latest
    steps:
      - name: Download unsigned APKs
        uses: actions/download-artifact@v5.0.0
        with:
          path: upstream/unsigned
          merge-multiple: true
      - name: Sign APKs
        uses: Tlaster/android-sign@v1.2.2
        with:
          releaseDirectory: upstream/unsigned
          signingKeyBase64: "${{ secrets.KREATE_KEYSTORE }}"
          keyStorePassword: "${{ secrets.KREATE_KEYSTORE_PASSWD }}"
          alias: "${{ secrets.KREATE_KEY_ALIAS }}"
          keyPassword: "${{ secrets.KREATE_KEY_PASSWD }}"
          output: signed
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
      - name: Remove trails
        run: |
          for f in signed/*.apk; do mv "$f" "${f//-signed}"; done
      - name: Upload signed APKs
        uses: actions/upload-artifact@v4.6.2
        with:
          name: signed-apks
          path: signed/*.apk

  upload-to-release:
    needs: [build_time, versioning, sign-apks]
    runs-on: ubuntu-latest
    steps:
      - name: Download signed APKs
        uses: actions/download-artifact@v5.0.0
        with:
          name: signed-apks
      - name: Set unique release tag
        id: set_tag
        run: |
          UNIQUE_TAG="v${{ needs.versioning.outputs.downstream }}-${{ needs.build_time.outputs.date }}"
          echo "tag_name=$UNIQUE_TAG" >> $GITHUB_OUTPUT
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: '*.apk'
          tag_name: ${{ steps.set_tag.outputs.tag_name }}
          name: ${{ steps.set_tag.outputs.tag_name }}
          make_latest: true
          token: ${{ secrets.RELEASE_TOKEN }}
          generate_release_notes: true
          body: |
            ## What's `Kreate-izzy.apk`
            This is APK built specifically for IzzyOnDroid with update checker disabled. You shouldn't download this version here.
            ## Verification
            Always check for signature before installing any APK.
            ## Changelogs
            Please visit [wiki/changelogs](https://github.com/knighthat/Kreate/wiki/Changelogs) for details.
